# Generated by Django 2.2.12 on 2020-04-12 16:26

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='power_reading',
            field=djongo.models.fields.ListField(default=[1]),
            preserve_default=False,
        ),
    ]
