# Generated by Django 2.2.12 on 2020-04-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_device_power_reading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='power_reading',
        ),
    ]
